/** Lifecycle states for a {@link ReleaseRecord}. `frozen` is set by {@link ReleaseManager.setFreezeWindow}, not chosen directly. */
export type ReleaseStatus = 'planning' | 'in_progress' | 'frozen' | 'released' | 'cancelled'

/** A Linear ticket as captured in a release manifest — a trimmed projection of `LinearTicket`. */
export interface ManifestTicket {
  id: string
  identifier: string
  title: string
  description?: string
  status: string
  priority: number
  labels: string[]
  assignee?: string
  url?: string
}

/** The point-in-time snapshot of a release's scope, generated by {@link ReleaseManager.buildManifest} and persisted on the release record. */
export interface ReleaseManifest {
  releaseId: string
  version: string
  generatedAt: string
  linearCycleId?: string
  tickets: ManifestTicket[]
  summary: {
    total: number
    byStatus: Record<string, number>
    byPriority: Record<number, number>
  }
}

/** A row from the `releases` table, as returned by {@link ReleaseManager}. */
export interface ReleaseRecord {
  id: string
  version: string
  branch: string
  status: ReleaseStatus
  linearCycleId?: string
  manifest?: ReleaseManifest
  notes?: string
  freezeAt?: Date
  releasedAt?: Date
  createdAt: Date
  updatedAt: Date
}

/** Options for {@link ReleaseManager.create}. */
export interface CreateReleaseOptions {
  branch: string
  linearCycleId?: string
  freezeAt?: Date
}
